build:
	g++ src/*.cpp \
	-I/opt/homebrew/Cellar/sfml/2.6.1/include \
	-L/opt/homebrew/Cellar/sfml/2.6.1/lib \
	-lsfml-graphics \
	-lsfml-window \
	-lsfml-system \
	--std=c++11 \
	-o sfml-app
run:
	./sfml-app config.cfg
clean:
	rm sfml-app
win:
	g++ src/*.cpp \
	-I"C:\Users\aranr\OneDrive\Documents\SFML-2.6.1-windows-gcc-13.1.0-mingw-64-bit\SFML-2.6.1\include" \
	-L"C:\Users\aranr\OneDrive\Documents\SFML-2.6.1-windows-gcc-13.1.0-mingw-64-bit\SFML-2.6.1\lib" \
	-lsfml-graphics \
	-lsfml-window \
	-lsfml-system \
	--std=c++11 \
	-o sfml-app
